; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter = 
	+<main.cpp>
	-<esp32_main.cpp>
	-<CameraWebServer_AP.cpp>
	-<app_httpd.cpp>
lib_deps = 
	arkhipenko/TaskScheduler @ ^3.8.5
	thijse/ArduinoLog @ ^1.1.1
	teckel12/NewPing @ ^1.9.7
	arduino-libraries/Servo @ ^1.2.1
	adafruit/Adafruit MPU6050 @ ^2.2.6
	adafruit/Adafruit Unified Sensor @ ^1.1.14
	adafruit/Adafruit BusIO @ ^1.16.0
	andrealombardo/L298N @ ^2.0.3
	adafruit/Adafruit NeoPixel@^1.15.4

[env:esp32_cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
board_build.psram = enabled
board_build.partitions = huge_app.csv
build_src_filter = 
	+<esp32_main.cpp>
	+<CameraWebServer_AP.cpp>
	+<app_httpd.cpp>
	-<main.cpp>
build_flags = 
	-DBOARD_HAS_PSRAM
	-DCAMERA_MODEL_AI_THINKER
lib_deps = 
	espressif/esp32-camera @ ^2.0.4
	thijse/ArduinoLog @ ^1.1.1
	arkhipenko/TaskScheduler @ ^3.8.5
	adafruit/Adafruit NeoPixel@^1.15.4

[env:esp32cam]
extends = env:esp32_cam
